### ISSUE TITLE
Great tool

### ISSUE THREAD

**Issue by aikruger** [Mara-Li/obsidian-customizable-menu#1]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Is your feature related to a problem ?

Many thanks for doing this little tool it works brilliantly

### What solution do you want to see ?

It needs more exposure

### OS

Windows

### Obsidian information

```bash session
latest version
```

### Plugin version

current

**Comment by Mara-Li** [comment]
Thanks :D
